# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'reactify' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactInstagram
  pod 'FBSDKLoginKit'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage' 
  # pod 'Firebase/Auth'

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # target 'ReactInstagram-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  # target 'ReactInstagramTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end 

end 

# target 'ReactInstagram-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactInstagram-tvOS

  # target 'ReactInstagram-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

# end 
